# Generated by Django 2.2.6 on 2019-10-29 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191029_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='dewPointTemperature',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='minDewPointTemperature',
        ),
    ]
