# Generated by Django 2.2.6 on 2020-01-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_examination'),
    ]

    operations = [
        migrations.CreateModel(
            name='modelResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='examination',
            name='examinationTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
