# Generated by Django 2.2.6 on 2020-01-26 03:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200126_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelresult',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
